fix(launcher.py): Support GET and DELETE with Python 3
Prevents the following error when doing GET or DELETE
request:
builtins.TypeError: a bytes-like object is required, not 'str'

Closes #16